### ISSUE TITLE
PyPi.org / Pip install does not match github code

### ISSUE THREAD

**Issue by bwilso1** [clerie/mcuuid#1]
while using python 3 and venv (virtual environment) using `pip install mcuuid` downloads an `<project location>\Lib\site-packages\mcuuid\api.py` with lines 10 and 11 as.
```
from tools import is_valid_minecraft_username
from tools import is_valid_mojang_uuid
```

the code found on Github has lines 10 and 11 in `api.py` as

```
from mcuuid.tools import is_valid_minecraft_username
from mcuuid.tools import is_valid_mojang_uuid
```

if I revert the lines 10 and 11 to match the github code, everything works fine.  But as of right now, the pip install method will yield the following errors

```
>>> from mcuuid.api import GetPlayerData
ModuleNotFoundError: No module named 'tools'
```

If needed, here is how to use venv & re-create the bug
have python 3 installed
in a terminal type `venv . ` to create in current directory or `venv <your desired directory`
from the project folder execute \Scripts\activate.bat
type `pip install mcuuid`
navigate to `<project location>\Lib\site-packages\mcuuid\api.py`

**Comment by christopher-besch** [comment]
I can confirm the problem (even without venv); the provided solution is working.
But I would still appreciate a working version using pip.

**Comment by RyanWoodruff** [comment]
Also can confirm the issue.

**Comment by clerie** [comment]
Hey, the code was really shit and I've learned much in the last years. I refactored this module into to `MCUUID` class, but made a wrapper so you can still use the old module classes with this. I hope you find it still useful :heart:
