### ISSUE TITLE
The server has not found anything matching the request URI

### ISSUE THREAD

**Issue by kiroffYT** [clerie/mcuuid#4]
I enter the code from the examples:
```
from mcuuid import MCUUID

player = MCUUID(uuid="a2080281c2784181b961d99ed2f3347c")
print(player.name)
```

But every damn time this error appears:
```
C:\Users\Home\pythonProject\sp5-stats-project\venv\Scripts\python.exe C:\Users\Home\pythonProject\sp5-stats-project\statsGenerator.py 
{"error":"Not Found","errorMessage":"The server has not found anything matching the request URI"}

Process finished with exit code 0
```

How to fix this? I tried everything, but NOTHING helped.

**Comment by clerie** [comment]
Hi @kiroffYT, I wasn't able to reproduce the error.

```
>>> from mcuuid import MCUUID
>>> player = MCUUID(uuid="a2080281c2784181b961d99ed2f3347c")
>>> print(player.name)
Gronkh
```

Please make sure you use the current version of this package (v1.1.0). It may be possible you have ran into a temporary server problem too.

Please check again an reach back if the issue still exist. In that case please give more context, like explain in which setup you run the code in and give some snippets of the actual code.
